# Generated by Django 3.1.4 on 2020-12-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='image',
            field=models.ImageField(default='images/default_pic/default_profile_pic.jpg', upload_to='images/watches_pics/'),
            preserve_default=False,
        ),
    ]
