# Generated by Django 3.1.4 on 2020-12-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0002_watch_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchdescription',
            name='case_shape',
            field=models.CharField(choices=[('circle', 'Circle'), ('square', 'Square'), ('rectangle', 'Rectangle'), ('triangle', 'Triangle'), ('other', 'Other')], default=('circle', 'Circle'), max_length=20),
        ),
        migrations.AlterField(
            model_name='watchdescription',
            name='chronograph',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default=('no', 'No'), max_length=20),
        ),
    ]
